PS1='\[\e[1;32m\][\u:\w]\$\[\e[m\] '

alias grep='grep --color=auto'
alias psg='ps -ef |grep -i'
alias ls='ls --color'
alias la='ls -A'
alias ll='ls -lh'
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
