set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -g prefix ^a
set -g allow-rename off
setw -g mode-keys vi

unbind ^b
bind a send-prefix

bind ^a selectp -l
bind h selectp -L
bind l selectp -R
bind k selectp -U
bind j selectp -D

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind -n C-PageUp  previous-window
bind -n C-PageDown next-window

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind r source-file ~/.tmux.conf

set -g status-left ''
set -g status-right ''
set -g status-fg colour229
set -g status-bg colour236
setw -g window-status-current-bg colour242
setw -g window-status-bg colour238

set -g pane-border-fg colour228
set -g pane-active-border-fg colour224
